In [6]:
import numpy as np 

# Desafio 1 - Dado o seguinte array, some o valor 10 a cada elemento usando broadcasting.
array = np.array([10, 20, 30, 40, 50])
valor = 10
print(array + valor)

print('-'*40)
# Desafio 2 - Dada a matriz abaixo, subtraia o array [5, 5] de cada linha usando broadcasting.
matriz = np.array([[5, 10], [15, 20], [25, 30]])
vetor = np.array([5, 5])

print(matriz - vetor)
print('-'*40)

# Desafio 3 - Multiplique cada coluna da matriz abaixo pelo array [2, 3].
matriz = np.array([[5, 10], [15, 20], [25, 30]])
vetor = np.array([2, 3])

print(matriz * vetor)


[20 30 40 50 60]
----------------------------------------
[[ 0  5]
 [10 15]
 [20 25]]
----------------------------------------
[[10 30]
 [30 60]
 [50 90]]
