In [4]:
import numpy as np

pesos_1 = np.array([10, 20, 30])
pesos_2 = np.array([40, 50, 60])

# Soma os valores correspondentes em cada array
print(pesos_1 + pesos_2)

pesos_1 - pesos_2

pesos_1 * pesos_2

pesos_1 / pesos_2

[50 70 90]


array([0.25, 0.4 , 0.5 ])

In [ ]:
import numpy as np

pesos_1 = np.array([10, 20, 30])
pesos_2 = np.array([40, 50, 60])


# soma
pesos_1

# Funções estatísticas mais utilizadas

In [9]:
import numpy as np

numeros = np.array([4, 9, 2, 10, 7])

print(np.min(numeros))
print(np.max(numeros))
print(np.mean(numeros))
print(np.median(numeros))
print(np.sum(numeros))

# Para encontrar o índice (ou seja, a localização)
print('-'*30)
print(np.argmin(numeros))
print(np.argmax(numeros))

# Soma cumulativa
print(np.cumsum(numeros))


2
10
6.4
7.0
32
------------------------------
2
3
[ 4 13 15 25 32]


In [10]:
decimais = np.array([2.5, 3.2, 4.8])
print(np.round(decimais))

[2. 3. 5.]


# Funções estatísticas de um jeito fácil

In [6]:
import numpy as np

# Exponenciação 5³ 
print(np.power(5, 3))
numeros = np.array([1, 2, 3])
print(np.power(numeros, 2))
print('-'*30)

# Logarítmo natural
print(np.log(7))
print(np.log(numeros))
print('-'*30)

# Raíz quadrada
print(np.sqrt(16))
numeros = np.array([1, 4, 9, 16])
print(np.sqrt(numeros))
print('-'*30)

# Desvio padrão (quão distante da média os valores estão)
dados = np.array([50, 50, 47, 53, 52])
print(np.std(dados))




125
[1 4 9]
------------------------------
1.9459101490553132
[0.         0.69314718 1.09861229]
------------------------------
4.0
[1. 2. 3. 4.]
------------------------------
2.0591260281974
